### ISSUE TITLE
--root argument not found in typst 0.6.0

### ISSUE THREAD

**Issue by slashformotion** [yusancky/setup-typst#11]
![image](https://github.com/yusancky/setup-typst/assets/45801817/82606c7f-6771-45be-811f-70475cc6ac11)

I am confused, your action download a version of typst that does not have the --root argument even tho it's in the changelog for v0.6.0
See: https://typst.app/docs/changelog/

**Comment by yusancky** [comment]
> Arguments that are command to all commands have been moved to before the subcommand, meaning that `font-path` and `root` must precede the command, here is an example:
> ```
> typst --root ../my_project build main.typ
> ```

See typst/typst#468 for more information.

**Comment by slashformotion** [comment]
thanks
